/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PlaceOrderRouteImport } from './routes/place-order'
import { Route as OrderRouteImport } from './routes/order'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YoutubeIndexRouteImport } from './routes/youtube/index'
import { Route as ProductIndexRouteImport } from './routes/product/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as ProductProductidRouteImport } from './routes/product/$productid'
import { Route as PostsPostidRouteImport } from './routes/posts/$postid'
import { Route as YoutubeProfileRouteRouteImport } from './routes/youtube/profile/route'
import { Route as YoutubeProfileIndexRouteImport } from './routes/youtube/profile/index'
import { Route as YoutubeProfileVirajRouteImport } from './routes/youtube/profile/viraj'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceOrderRoute = PlaceOrderRouteImport.update({
  id: '/place-order',
  path: '/place-order',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeIndexRoute = YoutubeIndexRouteImport.update({
  id: '/youtube/',
  path: '/youtube/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIndexRoute = ProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductidRoute = ProductProductidRouteImport.update({
  id: '/product/$productid',
  path: '/product/$productid',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostidRoute = PostsPostidRouteImport.update({
  id: '/posts/$postid',
  path: '/posts/$postid',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeProfileRouteRoute = YoutubeProfileRouteRouteImport.update({
  id: '/youtube/profile',
  path: '/youtube/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeProfileIndexRoute = YoutubeProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => YoutubeProfileRouteRoute,
} as any)
const YoutubeProfileVirajRoute = YoutubeProfileVirajRouteImport.update({
  id: '/viraj',
  path: '/viraj',
  getParentRoute: () => YoutubeProfileRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/place-order': typeof PlaceOrderRoute
  '/signup': typeof SignupRoute
  '/youtube/profile': typeof YoutubeProfileRouteRouteWithChildren
  '/posts/$postid': typeof PostsPostidRoute
  '/product/$productid': typeof ProductProductidRoute
  '/posts/': typeof PostsIndexRoute
  '/product/': typeof ProductIndexRoute
  '/youtube/': typeof YoutubeIndexRoute
  '/youtube/profile/viraj': typeof YoutubeProfileVirajRoute
  '/youtube/profile/': typeof YoutubeProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/place-order': typeof PlaceOrderRoute
  '/signup': typeof SignupRoute
  '/posts/$postid': typeof PostsPostidRoute
  '/product/$productid': typeof ProductProductidRoute
  '/posts': typeof PostsIndexRoute
  '/product': typeof ProductIndexRoute
  '/youtube': typeof YoutubeIndexRoute
  '/youtube/profile/viraj': typeof YoutubeProfileVirajRoute
  '/youtube/profile': typeof YoutubeProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/order': typeof OrderRoute
  '/place-order': typeof PlaceOrderRoute
  '/signup': typeof SignupRoute
  '/youtube/profile': typeof YoutubeProfileRouteRouteWithChildren
  '/posts/$postid': typeof PostsPostidRoute
  '/product/$productid': typeof ProductProductidRoute
  '/posts/': typeof PostsIndexRoute
  '/product/': typeof ProductIndexRoute
  '/youtube/': typeof YoutubeIndexRoute
  '/youtube/profile/viraj': typeof YoutubeProfileVirajRoute
  '/youtube/profile/': typeof YoutubeProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/login'
    | '/order'
    | '/place-order'
    | '/signup'
    | '/youtube/profile'
    | '/posts/$postid'
    | '/product/$productid'
    | '/posts/'
    | '/product/'
    | '/youtube/'
    | '/youtube/profile/viraj'
    | '/youtube/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/login'
    | '/order'
    | '/place-order'
    | '/signup'
    | '/posts/$postid'
    | '/product/$productid'
    | '/posts'
    | '/product'
    | '/youtube'
    | '/youtube/profile/viraj'
    | '/youtube/profile'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/contact'
    | '/login'
    | '/order'
    | '/place-order'
    | '/signup'
    | '/youtube/profile'
    | '/posts/$postid'
    | '/product/$productid'
    | '/posts/'
    | '/product/'
    | '/youtube/'
    | '/youtube/profile/viraj'
    | '/youtube/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  OrderRoute: typeof OrderRoute
  PlaceOrderRoute: typeof PlaceOrderRoute
  SignupRoute: typeof SignupRoute
  YoutubeProfileRouteRoute: typeof YoutubeProfileRouteRouteWithChildren
  PostsPostidRoute: typeof PostsPostidRoute
  ProductProductidRoute: typeof ProductProductidRoute
  PostsIndexRoute: typeof PostsIndexRoute
  ProductIndexRoute: typeof ProductIndexRoute
  YoutubeIndexRoute: typeof YoutubeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place-order': {
      id: '/place-order'
      path: '/place-order'
      fullPath: '/place-order'
      preLoaderRoute: typeof PlaceOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube/': {
      id: '/youtube/'
      path: '/youtube'
      fullPath: '/youtube/'
      preLoaderRoute: typeof YoutubeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/': {
      id: '/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof ProductIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productid': {
      id: '/product/$productid'
      path: '/product/$productid'
      fullPath: '/product/$productid'
      preLoaderRoute: typeof ProductProductidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postid': {
      id: '/posts/$postid'
      path: '/posts/$postid'
      fullPath: '/posts/$postid'
      preLoaderRoute: typeof PostsPostidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube/profile': {
      id: '/youtube/profile'
      path: '/youtube/profile'
      fullPath: '/youtube/profile'
      preLoaderRoute: typeof YoutubeProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube/profile/': {
      id: '/youtube/profile/'
      path: '/'
      fullPath: '/youtube/profile/'
      preLoaderRoute: typeof YoutubeProfileIndexRouteImport
      parentRoute: typeof YoutubeProfileRouteRoute
    }
    '/youtube/profile/viraj': {
      id: '/youtube/profile/viraj'
      path: '/viraj'
      fullPath: '/youtube/profile/viraj'
      preLoaderRoute: typeof YoutubeProfileVirajRouteImport
      parentRoute: typeof YoutubeProfileRouteRoute
    }
  }
}

interface YoutubeProfileRouteRouteChildren {
  YoutubeProfileVirajRoute: typeof YoutubeProfileVirajRoute
  YoutubeProfileIndexRoute: typeof YoutubeProfileIndexRoute
}

const YoutubeProfileRouteRouteChildren: YoutubeProfileRouteRouteChildren = {
  YoutubeProfileVirajRoute: YoutubeProfileVirajRoute,
  YoutubeProfileIndexRoute: YoutubeProfileIndexRoute,
}

const YoutubeProfileRouteRouteWithChildren =
  YoutubeProfileRouteRoute._addFileChildren(YoutubeProfileRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  OrderRoute: OrderRoute,
  PlaceOrderRoute: PlaceOrderRoute,
  SignupRoute: SignupRoute,
  YoutubeProfileRouteRoute: YoutubeProfileRouteRouteWithChildren,
  PostsPostidRoute: PostsPostidRoute,
  ProductProductidRoute: ProductProductidRoute,
  PostsIndexRoute: PostsIndexRoute,
  ProductIndexRoute: ProductIndexRoute,
  YoutubeIndexRoute: YoutubeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
