/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as YoutubeIndexRouteImport } from './routes/youtube/index'
import { Route as PostsIndexRouteImport } from './routes/posts/index'
import { Route as PostsPostidRouteImport } from './routes/posts/$postid'
import { Route as YoutubeProfileRouteRouteImport } from './routes/youtube/profile/route'
import { Route as YoutubeProfileIndexRouteImport } from './routes/youtube/profile/index'
import { Route as YoutubeProfileVirajRouteImport } from './routes/youtube/profile/viraj'

const ContactLazyRouteImport = createFileRoute('/contact')()

const ContactLazyRoute = ContactLazyRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeIndexRoute = YoutubeIndexRouteImport.update({
  id: '/youtube/',
  path: '/youtube/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostidRoute = PostsPostidRouteImport.update({
  id: '/posts/$postid',
  path: '/posts/$postid',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeProfileRouteRoute = YoutubeProfileRouteRouteImport.update({
  id: '/youtube/profile',
  path: '/youtube/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const YoutubeProfileIndexRoute = YoutubeProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => YoutubeProfileRouteRoute,
} as any)
const YoutubeProfileVirajRoute = YoutubeProfileVirajRouteImport.update({
  id: '/viraj',
  path: '/viraj',
  getParentRoute: () => YoutubeProfileRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactLazyRoute
  '/youtube/profile': typeof YoutubeProfileRouteRouteWithChildren
  '/posts/$postid': typeof PostsPostidRoute
  '/posts/': typeof PostsIndexRoute
  '/youtube/': typeof YoutubeIndexRoute
  '/youtube/profile/viraj': typeof YoutubeProfileVirajRoute
  '/youtube/profile/': typeof YoutubeProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactLazyRoute
  '/posts/$postid': typeof PostsPostidRoute
  '/posts': typeof PostsIndexRoute
  '/youtube': typeof YoutubeIndexRoute
  '/youtube/profile/viraj': typeof YoutubeProfileVirajRoute
  '/youtube/profile': typeof YoutubeProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactLazyRoute
  '/youtube/profile': typeof YoutubeProfileRouteRouteWithChildren
  '/posts/$postid': typeof PostsPostidRoute
  '/posts/': typeof PostsIndexRoute
  '/youtube/': typeof YoutubeIndexRoute
  '/youtube/profile/viraj': typeof YoutubeProfileVirajRoute
  '/youtube/profile/': typeof YoutubeProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/youtube/profile'
    | '/posts/$postid'
    | '/posts/'
    | '/youtube/'
    | '/youtube/profile/viraj'
    | '/youtube/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/posts/$postid'
    | '/posts'
    | '/youtube'
    | '/youtube/profile/viraj'
    | '/youtube/profile'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/youtube/profile'
    | '/posts/$postid'
    | '/posts/'
    | '/youtube/'
    | '/youtube/profile/viraj'
    | '/youtube/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactLazyRoute: typeof ContactLazyRoute
  YoutubeProfileRouteRoute: typeof YoutubeProfileRouteRouteWithChildren
  PostsPostidRoute: typeof PostsPostidRoute
  PostsIndexRoute: typeof PostsIndexRoute
  YoutubeIndexRoute: typeof YoutubeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube/': {
      id: '/youtube/'
      path: '/youtube'
      fullPath: '/youtube/'
      preLoaderRoute: typeof YoutubeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postid': {
      id: '/posts/$postid'
      path: '/posts/$postid'
      fullPath: '/posts/$postid'
      preLoaderRoute: typeof PostsPostidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube/profile': {
      id: '/youtube/profile'
      path: '/youtube/profile'
      fullPath: '/youtube/profile'
      preLoaderRoute: typeof YoutubeProfileRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youtube/profile/': {
      id: '/youtube/profile/'
      path: '/'
      fullPath: '/youtube/profile/'
      preLoaderRoute: typeof YoutubeProfileIndexRouteImport
      parentRoute: typeof YoutubeProfileRouteRoute
    }
    '/youtube/profile/viraj': {
      id: '/youtube/profile/viraj'
      path: '/viraj'
      fullPath: '/youtube/profile/viraj'
      preLoaderRoute: typeof YoutubeProfileVirajRouteImport
      parentRoute: typeof YoutubeProfileRouteRoute
    }
  }
}

interface YoutubeProfileRouteRouteChildren {
  YoutubeProfileVirajRoute: typeof YoutubeProfileVirajRoute
  YoutubeProfileIndexRoute: typeof YoutubeProfileIndexRoute
}

const YoutubeProfileRouteRouteChildren: YoutubeProfileRouteRouteChildren = {
  YoutubeProfileVirajRoute: YoutubeProfileVirajRoute,
  YoutubeProfileIndexRoute: YoutubeProfileIndexRoute,
}

const YoutubeProfileRouteRouteWithChildren =
  YoutubeProfileRouteRoute._addFileChildren(YoutubeProfileRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactLazyRoute: ContactLazyRoute,
  YoutubeProfileRouteRoute: YoutubeProfileRouteRouteWithChildren,
  PostsPostidRoute: PostsPostidRoute,
  PostsIndexRoute: PostsIndexRoute,
  YoutubeIndexRoute: YoutubeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
